permissions:
  contents: read

steps:
  - uses: actions/checkout@v4

  - name: Debug secrets
    run: |
      echo "CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID != '' }}"
      echo "CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET != '' }}"
      echo "TENANT_ID: ${{ secrets.AZURE_TENANT_ID != '' }}"

  - name: Azure Login using SP
    uses: azure/login@v2
    with:
      auth-type: SERVICE_PRINCIPAL
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
